const{Builder,By,Key}=require("selenium-webdriver"),chrome=require("selenium-webdriver/chrome");
class PreSalesJourneyValidator{
constructor(t={}){
this.startUrl=t.startUrl||"https://starhubltd-tst.outsystemsenterprise.com/personal/login",this.credentials=t.credentials||{},this.config=t.journeyConfig||{},this.maxAdobeWait=t.maxAdobeWait||6e4,this.networkQuietTime=t.networkQuietTime||4e3,this.pollInterval=t.pollInterval||250,this.timeout=t.timeout||9e4,this.driver=null,this.paymentOptionPrompt="2",this.payLaterPeriod=t.payLaterPeriod||null,this.simType=t.simType||null,this.result={startedAt:new Date().toISOString(),finishedAt:null,authentication:{},summary:{status:"NOT_RUN",steps:0,passed:0,failed:0,adobeHits:0,ecommerceEvents:0,pagesVisited:0,productsCaptured:0,ordersCaptured:0},pages:[],actions:[],products:[],orders:[],ecommerceEvents:[],hits:[],errors:[],selections:[]},this.seenHitKeys=new Set,this.lastRecordedPageName=""
}
async createDriver(){
if(this.driver)return this.driver;const t=new chrome.Options;return t.addArguments("--headless=new","--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--window-size=1920,1080","--disable-popup-blocking","--disable-notifications","--disable-background-networking","--disable-background-timer-throttling","--disable-renderer-backgrounding","--disable-features=TranslateUI"),t.setLoggingPrefs({performance:"ALL",browser:"ALL"}),this.driver=await new Builder().forBrowser("chrome").setChromeOptions(t).build(),this.driver
}
async close(){if(this.driver){try{await this.driver.quit()}catch(t){}this.driver=null}}
async sleep(t){return new Promise(e=>setTimeout(e,t))}
async drainPerformanceLogs(){try{return await this.driver.manage().logs().get("performance")}catch(t){return[]}}
parsePerformanceLog(t){try{return JSON.parse(t.message).message}catch(t){return null}}
parseParameterPairs(t){const e=[];if(!t)return e;let i=String(t);try{if(/^https?:/i.test(i)){const t=new URL(i);for(const[i,a]of t.searchParams.entries())e.push([i,a])}else{i=i.replace(/^\?/,"");const t=new URLSearchParams(i);for(const[i,a]of t.entries())e.push([i,a])}}catch(t){}return e}
parseHit(t,e="",i=""){const a=[...this.parseParameterPairs(t),...this.parseParameterPairs(e)],r={};for(const[t,e]of a)r[t]=e;let s="",n="";try{const e=new URL(t);n=e.pathname;const i=e.pathname.split("/"),a=i.findIndex(t=>"b"===t.toLowerCase());a>=0&&i[a+1]&&"ss"===i[a+1].toLowerCase()&&i[a+2]&&(s=i[a+2])}catch(t){}const o=[];for(const[t,e]of a){if("events"===t.toLowerCase())for(const t of String(e).split(",")){const e=t.trim();if(e){const i=e.split(":");o.push({name:i[0].trim(),value:i.slice(1).join(":").trim()})}}/^event\d+$/i.test(t)&&o.push({name:t,value:e||"1"})}const c={},l={};for(const[t,e]of a)(/^v\d+$/i.test(t)||/^evar\d+$/i.test(t))&&(c[t.toLowerCase()]=e),(/^c\d+$/i.test(t)||/^prop\d+$/i.test(t))&&(l[t.toLowerCase()]=e);return{timestamp:new Date().toISOString(),requestId:i||"",url:t,pathName:n,reportSuite:s,pageName:r.pageName||r.gn||r.v1||"",events:o.map(t=>t.name),eventDetails:o,eVars:c,props:l,products:r.products||"",orderId:r.purchaseID||r.purchaseId||r.transactionID||r.orderId||r.oid||"",revenue:r.purchaseamount||r.purchaseAmount||r.revenue||r.amount||"",rawQuery:r,postData:e||""}
}
async collectAdobeHits(){const t=[],e=await this.drainPerformanceLogs();for(const i of e){const e=this.parsePerformanceLog(i);if(!e||"Network.requestWillBeSent"!==e.method)continue;const a=e.params&&e.params.request;if(!a||!a.url||!/\/b\/ss\//i.test(a.url))continue;const r=this.parseHit(a.url,a.postData||"",e.params.requestId||""),s=`${r.requestId}|${r.url}|${r.postData}`;this.seenHitKeys.has(s)||(this.seenHitKeys.add(s),t.push(r))}return t}
async captureAdobeWindow(t,e={}){const i=e.timeout||(e.isPageLoad?this.maxAdobeWait:2e4),a=e.quietTime||this.networkQuietTime,r=Date.now();let s=null;const n=[];for(;Date.now()-r<i;){const t=await this.collectAdobeHits();t.length&&(n.push(...t),s=Date.now()),n.length&&s&&Date.now()-s>=a?0:await this.sleep(this.pollInterval)}return n.length&&this.addHitData(n),n}
async waitForElement(t,e=6e4){const i=Date.now();for(;Date.now()-i<e;){try{for(const e of await this.driver.findElements(t))if(await e.isDisplayed().catch(()=>!1)&&await e.isEnabled().catch(()=>!1))return e}catch(t){}await this.sleep(300)}throw new Error(`Element not found within ${e}ms: ${JSON.stringify(t)}`)}
async visibleElements(t){const e=await this.driver.findElements(t),i=[];for(const t of e)try{await t.isDisplayed()&&await t.isEnabled()&&i.push(t)}catch(t){}return i}
async textOf(t){try{return(await t.getText()).replace(/\s+/g," ").trim()}catch(t){return""}}
async clickElement(t,e=""){await this.driver.executeScript("arguments[0].scrollIntoView({block:'center',inline:'center'});",t).catch(()=>{}),await this.sleep(300);try{await t.click()}catch(e){await this.driver.executeScript("arguments[0].click();",t)}}
async waitForUrlPrefix(t,e=6e4){const i=Date.now();for(;Date.now()-i<e;){try{const e=await this.driver.getCurrentUrl();if(e&&e.toLowerCase().startsWith(t.toLowerCase()))return e}catch(t){}await this.sleep(400)}throw new Error(`Timed out waiting for URL prefix: ${t}. Current URL: ${await this.driver.getCurrentUrl()}`)}
async waitForPageReady(t=6e4){const e=Date.now();for(;Date.now()-e<t;){try{const t=await this.driver.executeScript("return document.readyState");if("complete"===t||"interactive"===t)return}catch(t){}await this.sleep(250)}}
async getPageName(){try{return await this.driver.executeScript(`try{for(const l of [window.adobeDataLayer,window.dataLayer])if(Array.isArray(l))for(let i=l.length-1;i>=0;i--){const x=l[i];if(x&&typeof x==="object"){if(x.pageName)return String(x.pageName).trim();if(x.page&&x.page.pageName)return String(x.page.pageName).trim();if(x.pageData&&x.pageData.pageName)return String(x.pageData.pageName).trim()}}}catch(e){}return""`)}catch(t){return""}}
async waitForPageName(t="",e=3500){const i=Date.now();for(;Date.now()-i<e;){const e=String(await this.getPageName()).trim();if(e&&e!==t)return e;await this.sleep(250)}return""}
async recordPage(t,e=""){await this.waitForPageReady();const i=await this.driver.getCurrentUrl(),a=await this.driver.getTitle().catch(()=>"");this.currentPageUrl=i;const r=await this.waitForPageName(this.lastRecordedPageName),s=await this.captureAdobeWindow(`${t} pageLoad`,{isPageLoad:true}),n=[...s].reverse().map(t=>String(t.pageName||"").trim()).find(Boolean)||r||"";this.lastRecordedPageName=n||this.lastRecordedPageName;const o=s.length?s:this.result.hits.slice(-10).filter(t=>String(t.pageName||"").trim()===n),c=[...new Set(o.flatMap(t=>t.events||[]))];return this.result.pages.push({step:t,url:i,expectedPrefix:e,title:a,pageName:n,pageLoadCaptured:s.length>0||!!n,adobeHitCount:o.length,eventsFound:c,status:s.length||n?"PASS":"FAIL",hits:o}),this.result.pages[this.result.pages.length-1]}
recordAction(t,e,i,a,r){const s=[...new Set((a||[]).flatMap(t=>t.events||[]))],n={action:t,label:e,value:i||"",pageUrl:r||this.currentPageUrl||"",timestamp:new Date().toISOString(),adobeHitCount:(a||[]).length,events:s,hits:a||[]};return this.result.actions.push(n),n}
addHitData(t){for(const e of t){this.result.hits.push(e);for(const t of e.eventDetails||[])this.result.ecommerceEvents.push({event:t.name,value:t.value,pageName:e.pageName,pageUrl:this.currentPageUrl||e.url,timestamp:e.timestamp,products:e.products,orderId:e.orderId,revenue:e.revenue,hitUrl:e.url});e.products&&this.result.products.push({pageUrl:this.currentPageUrl||e.url,pageName:e.pageName,products:e.products,events:e.events,eVars:e.eVars,props:e.props,timestamp:e.timestamp}),(e.orderId||e.revenue||e.events.some(t=>/purchase|order.?success/i.test(t)))&&this.result.orders.push({pageUrl:this.currentPageUrl||e.url,pageName:e.pageName,orderId:e.orderId,revenue:e.revenue,products:e.products,events:e.events,eVars:e.eVars,props:e.props,timestamp:e.timestamp})}}
async navigateAndRecord(t,e,i){await this.drainPerformanceLogs(),await this.driver.get(i),await this.waitForUrlPrefix(e),this.currentPageUrl=await this.driver.getCurrentUrl();return this.recordPage(t,e)}
async clickAndRecord(t,e,i="",a=""){await this.drainPerformanceLogs(),await e();const r=await this.captureAdobeWindow(t);return i&&await this.waitForUrlPrefix(i),this.currentPageUrl=await this.driver.getCurrentUrl(),this.recordAction("CTA",a||t,"",r,this.currentPageUrl),r}

async login(){
console.log("\n[1] Login");const t=this.config.startUrl||this.startUrl;await this.drainPerformanceLogs(),await this.driver.get(t),await this.sleep(3e3);let e=await this.driver.getCurrentUrl();if(/invalid-permissions/i.test(e)){const t=await this.driver.getTitle().catch(()=>"");const i=await this.driver.executeScript("return document.body?document.body.innerText:''").catch(()=>"");this.result.selections.push({type:"Login Permission Failure",requestedUrl:this.startUrl,redirectedUrl:e,title:t,bodyText:String(i).slice(0,5000)});throw new Error(`StarHub redirected Render to invalid-permissions before login. URL: ${e}. This is an access/permission issue, not a login-field selector issue.`)}await this.waitForPageReady(3e4);let i=null,a=null;const r=Date.now();for(;Date.now()-r<3e4&&!i&&!a;){await this.driver.switchTo().defaultContent().catch(()=>{});try{for(const t of await this.driver.findElements(By.css("input"))){if(!await t.isDisplayed().catch(()=>!1))continue;const e=((await t.getAttribute("type").catch(()=>""))+" "+(await t.getAttribute("name").catch(()=>""))+" "+(await t.getAttribute("id").catch(()=>""))+" "+(await t.getAttribute("placeholder").catch(()=>""))+" "+(await t.getAttribute("autocomplete").catch(()=>""))).toLowerCase(),r=(await t.getAttribute("type").catch(()=>"")).toLowerCase();"password"===r?a||(a=t):i||(/email|user.?name|hub.?id|login|account/.test(e)||"text"===r)&&(i=t)}if(i&&a)break;for(const t of await this.driver.findElements(By.css("iframe"))){if(i&&a)break;try{await this.driver.switchTo().defaultContent(),await this.driver.switchTo().frame(t);for(const t of await this.driver.findElements(By.css("input"))){if(!await t.isDisplayed().catch(()=>!1))continue;const e=((await t.getAttribute("type").catch(()=>""))+" "+(await t.getAttribute("name").catch(()=>""))+" "+(await t.getAttribute("id").catch(()=>""))+" "+(await t.getAttribute("placeholder").catch(()=>""))+" "+(await t.getAttribute("autocomplete").catch(()=>""))).toLowerCase(),r=(await t.getAttribute("type").catch(()=>"")).toLowerCase();"password"===r?a||(a=t):i||(/email|user.?name|hub.?id|login|account/.test(e)||"text"===r)&&(i=t)}}catch(t){await this.driver.switchTo().defaultContent().catch(()=>{})}}}catch(t){}if(!i||!a)await this.sleep(500)}
if(!i||!a){await this.driver.switchTo().defaultContent().catch(()=>{});const t=await this.driver.getCurrentUrl();if(/invalid-permissions/i.test(t))throw new Error(`StarHub redirected Render to invalid-permissions before login. URL: ${t}. Check test-site permissions and Render access.`);const e=await this.driver.executeScript("return document.body?document.body.innerText:''").catch(()=>""),r=await this.driver.getPageSource().catch(()=>"");this.result.selections.push({type:"Login Diagnostics",url:t,title:await this.driver.getTitle().catch(()=>""),bodyText:String(e).slice(0,5000),pageSource:String(r).slice(0,10000)});throw new Error(`Login fields not found. Username: ${i?"FOUND":"NOT FOUND"}, Password: ${a?"FOUND":"NOT FOUND"}, URL: ${t}`)}
await i.clear(),await i.sendKeys(this.credentials.hubId||""),await a.clear(),await a.sendKeys(this.credentials.hubPassword||"");const s=await this.visibleElements(By.xpath("//button[normalize-space(.)='Login' or .//*[normalize-space(.)='Login'] or contains(translate(normalize-space(.),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'login')] | //input[@type='submit']")).then(t=>t[0]).catch(()=>null);await this.drainPerformanceLogs(),s?await this.clickElement(s,"Login"):await a.sendKeys(Key.ENTER);const n=await this.captureAdobeWindow("Login CTA",{timeout:2e4,quietTime:2500});this.recordAction("CTA","Login","",n,await this.driver.getCurrentUrl()),await this.driver.switchTo().defaultContent().catch(()=>{}),await this.waitForUrlPrefix(this.config.homeUrlPrefix,9e4),this.currentPageUrl=await this.driver.getCurrentUrl(),this.result.authentication={status:"SUCCESS",account:"Test Account"},console.log("    Login successful. Landed on: "+this.currentPageUrl)
}

async stepHome(){console.log("\n[2] Mobile Plans / Landing"),await this.recordPage("Mobile Plans / Landing",this.config.homeUrlPrefix);const t=await this.visibleElements(By.xpath("//*[self::a or self::button or @role='button'][contains(normalize-space(.),'See more devices')]")).then(t=>t[0]);if(!t)throw new Error("CTA 'See more devices' was not found.");await this.clickAndRecord("See More Devices CTA",()=>this.clickElement(t,"See more devices"),this.config.deviceListingPrefix,"See more devices"),await this.recordPage("Mobile Device Listing",this.config.deviceListingPrefix)}
async isCurrentProductOutOfStock(){try{return await this.driver.executeScript(()=>{const t=t=>{if(!t)return!1;const e=getComputedStyle(t),i=t.getBoundingClientRect();return"none"!==e.display&&"hidden"!==e.visibility&&i.width>0&&i.height>0},e=/(?:out\s*of\s*stock|sold\s*out|currently\s*unavailable|not\s*available|unavailable|no\s*stock)/i,a=/(?:add\s*to\s*(?:cart|basket)|buy\s*now|available\s*now)/i,r=[];for(const e of["button","span","div","p"]){for(const i of document.querySelectorAll(e)){if(!t(i))continue;const t=String(i.innerText||i.textContent||"").replace(/\s+/g," ").trim();t&&t.length<=180&&e.test(t)&&r.push(t)}}return!Array.from(document.querySelectorAll("button,a,[role='button']")).some(e=>t(e)&&a.test(String(e.innerText||e.textContent||"")))&&r.length>0})}catch(t){return!1}}
async findIphone17ProMaxCards(t=9e4){const e=Date.now();for(;Date.now()-e<t;){const t=await this.driver.executeScript(()=>{const t=t=>String(t||"").replace(/\s+/g," ").trim(),e=[];return Array.from(document.querySelectorAll(".product-item-card")).forEach((i,a)=>{const r=t(i.innerText||i.textContent||""),s=i.querySelector(".content-section .f-h6, .content-section span.f-h6"),n=t(s?s.innerText||s.textContent:""),o=i.querySelector("img"),c=t(o?o.getAttribute("src"):""),l=`${n} ${r} ${c}`.toLowerCase();l.includes("iphone 17")&&(l.includes("iphone 17 pro max")||l.includes("iphone-17-pro-max"))&&e.push({index:a,model:n||"iPhone 17 Pro Max",text:r.slice(0,300),imageSrc:c})}),e}).catch(()=>[]);if(t.length)return t;await this.driver.executeScript("window.scrollTo(0,document.body.scrollHeight)").catch(()=>{}),await this.sleep(1200),await this.driver.executeScript("window.scrollTo(0,0)").catch(()=>{}),await this.sleep(1200)}return[]}
async chooseDevice(){console.log("\n[3] Mobile Device Listing -> Random iPhone 17 Pro Max");const t=new Set;let e="";for(let i=1;i<=8;i++){await this.waitForPageReady(9e4);(await this.driver.getCurrentUrl()).toLowerCase().startsWith(this.config.deviceListingPrefix.toLowerCase())||(await this.driver.get(this.config.deviceListingPrefix),await this.waitForUrlPrefix(this.config.deviceListingPrefix,9e4));const a=await this.findIphone17ProMaxCards(9e4);if(!a.length)throw new Error("No iPhone 17 Pro Max product cards were found.");let r=a.filter(e=>!t.has(e.model));r.length||(r=a);const s=r[Math.floor(Math.random()*r.length)];t.add(s.model),this.result.selections.push({type:"Device Attempt",value:s.model,attempt:i}),await this.drainPerformanceLogs();const n=await this.driver.executeScript(t=>{const e=Array.from(document.querySelectorAll(".product-item-card"))[t];if(!e)return!1;const i=[e.querySelector(".content-section > div[style*='cursor']"),e.querySelector(".image-section > div[style*='cursor']"),e.querySelector(".content-section"),e.querySelector(".image-section")].filter(Boolean)[0];return!!i&&(i.scrollIntoView({block:"center"}),i.click(),!0)},s.index).catch(()=>!1);if(!n){e=`iPhone 17 Pro Max card '${s.model}' could not be clicked.`;continue}const o=await this.captureAdobeWindow("iPhone 17 Pro Max prodClick",{timeout:3e4,quietTime:2500});this.recordAction("PRODUCT_CLICK","iPhone 17 Pro Max",s.model,o,await this.driver.getCurrentUrl());try{await this.waitForUrlPrefix(this.config.productPdpPrefix,9e4)}catch(t){e=t.message||String(t),await this.driver.get(this.config.deviceListingPrefix),await this.waitForUrlPrefix(this.config.deviceListingPrefix,9e4);continue}this.currentPageUrl=await this.driver.getCurrentUrl(),await this.recordPage("iPhone 17 Pro Max PDP",this.config.productPdpPrefix);if(!await this.isCurrentProductOutOfStock())return void this.result.selections.push({type:"Device Availability",value:`${s.model} - IN STOCK`,url:this.currentPageUrl,attempt:i});this.result.selections.push({type:"Device Availability",value:`${s.model} - OUT OF STOCK`,url:this.currentPageUrl,attempt:i}),await this.driver.get(this.config.deviceListingPrefix),await this.waitForUrlPrefix(this.config.deviceListingPrefix,9e4)}throw new Error(e||"Could not find an in-stock iPhone 17 Pro Max.")}
async getRadioGroups(){const t=await this.driver.findElements(By.css("input[type='radio']")),e=new Map;for(const i of t)try{if(!await i.isDisplayed()||!await i.isEnabled())continue;const t=await i.getAttribute("name")||"",a=await i.getAttribute("id")||"",r=t||a;if(!r)continue;const s=await this.findRadioLabel(i);s&&(e.has(r)||e.set(r,[]),e.get(r).push({radio:i,label:s}))}catch(t){}return[...e.entries()].map(([t,e])=>({key:t,options:e}))}
async findRadioLabel(t){const e=await t.getAttribute("id").catch(()=>"");if(e){const t=await this.driver.findElements(By.css(`label[for="${e.replace(/"/g,'\\"')}"]`));if(t.length)return this.textOf(t[0])}return this.driver.executeScript("return arguments[0].parentElement?arguments[0].parentElement.innerText:'';",t).then(t=>String(t||"").replace(/\s+/g," ").trim()).catch(()=>"")}
async selectRadioFromGroup(t,e){const i=t.options[Math.floor(Math.random()*t.options.length)],a=i.label;this.result.selections.push({type:e,value:a}),await this.drainPerformanceLogs(),await this.clickElement(i.radio,`${e} - ${a}`);const r=await this.captureAdobeWindow(`${e} selection`);this.recordAction("OPTION",e,a,r,await this.driver.getCurrentUrl())}
async choosePdpOptions(){
console.log("\n[4] iPhone 17 Pro Max PDP");const t=await this.getRadioGroups();let e=t.find(t=>/color|colour/i.test(t.key)),i=t.find(t=>/storage|size|capacity|gb/i.test(t.key)&&t!==e),a=new Set;e&&(await this.selectRadioFromGroup(e,"Color"),a.add(e.key)),i&&!a.has(i.key)&&(await this.selectRadioFromGroup(i,"Size/Storage"),a.add(i.key));const r="2",s=!1,n="Pay Today";console.log(`    Payment option forced to Option ${r}: ${n}`),this.result.selections.push({type:"Payment Option",option:r,value:n});let o=null,c=Date.now();for(;Date.now()-c<6e4;){try{for(const t of await this.driver.findElements(By.css('[aa_linktext="Pay today"],.shop-option.paymentoption-selection-option')))try{const e=(await t.getText()).replace(/\s+/g," ").trim().toLowerCase(),i=(await t.getAttribute("aa_linktext")||"").trim().toLowerCase();if(await t.isDisplayed()&&(i==="pay today"||e==="pay today"||e.includes("pay today"))){o=t;break}}catch(t){}}catch(t){}if(o)break;await this.sleep(500)}if(!o)throw new Error("Payment option 'Pay Today' was not found on PDP.");await this.drainPerformanceLogs(),await this.clickElement(o,"Pay Today");const l=await this.captureAdobeWindow("Pay Today selection",{timeout:3e4,quietTime:2500});this.recordAction("OPTION","Payment Option","Pay Today",l,await this.driver.getCurrentUrl());let d=null;c=Date.now();for(;Date.now()-c<6e4;){try{for(const t of await this.driver.findElements(By.css("#b5-b16-NextCTA button")))if(await t.isDisplayed().catch(()=>!1)&&await t.isEnabled().catch(()=>!1)){const e=await t.getAttribute("disabled"),i=await t.getAttribute("aria-disabled");if(null===e&&"true"!==String(i).toLowerCase()){d=t;break}}}catch(t){}if(d)break;await this.sleep(500)}if(!d)throw new Error("Next CTA was not found or did not become enabled on the iPhone PDP.");const h=await d.getAttribute("outerHTML").catch(()=>""),u=await d.getText(),w=await d.getAttribute("id")||"",g=await d.getAttribute("class")||"";this.result.selections.push({type:"PDP Next CTA",value:u||"Next",selector:"#b5-b16-NextCTA button",id:w,className:g,outerHTML:h}),await this.drainPerformanceLogs(),await this.clickElement(d,"Next - iPhone");const p=await this.captureAdobeWindow("Next - iPhone / scAdd",{timeout:3e4,quietTime:2500}),m=p.filter(t=>(t.events||[]).some(t=>/^scAdd$/i.test(t)));this.recordAction("CTA","Next - iPhone","Pay Today",p,await this.driver.getCurrentUrl()),this.result.selections.push({type:"PDP scAdd Validation",value:m.length?"scAdd captured":"scAdd not captured",scAddCaptured:m.length>0,scAddHitCount:m.length,hits:m}),await this.waitForUrlPrefix(this.config.intentPrefix,9e4),this.currentPageUrl=await this.driver.getCurrentUrl(),await this.recordPage("Intent Selection",this.config.intentPrefix)
}
async chooseIntent(){console.log("\n[5] Signup for New / Select Line");const t=await this.visibleElements(By.xpath("//*[contains(translate(normalize-space(.),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'sign up for a new line')]")).then(t=>t[0]);if(!t)throw new Error("'Sign up for a new line' option was not found.");const e=await this.textOf(t);this.result.selections.push({type:"Intent",value:e}),await this.drainPerformanceLogs(),await this.clickElement(t,"Sign up for a new line");const i=await this.captureAdobeWindow("Signup for new selection");this.recordAction("OPTION","Sign up for a new line",e,i,await this.driver.getCurrentUrl());const a=await this.visibleElements(By.xpath("//*[self::button or self::a or @role='button'][contains(normalize-space(.),'Next') or contains(normalize-space(.),'Continue')]")).then(t=>t[0]);if(!a)throw new Error("Next CTA was not found after intent selection.");await this.drainPerformanceLogs(),await this.clickElement(a,"Next - Intent Selection");const r=await this.captureAdobeWindow("Intent Next CTA");this.recordAction("CTA","Next - Intent Selection","Next",r,await this.driver.getCurrentUrl())}
async chooseStarPlan(){console.log("\n[6] Mobile Plan Selection");const t=await this.visibleElements(By.css(".sn-plan-card")).then(async t=>{for(const e of t)if(/5G Unlimited\+ Plus/i.test(await this.textOf(e)))return e;return null});if(!t)throw new Error("Mobile plan card '5G Unlimited+ Plus' was not found.");const e=await t.findElements(By.xpath(".//button[.//span[normalize-space()='Select plan'] or normalize-space()='Select plan']"));if(!e.length)throw new Error("'Select plan' CTA was not found.");await this.drainPerformanceLogs(),await this.clickElement(e[0],"Select plan - 5G Unlimited+ Plus");const i=await this.captureAdobeWindow("Mobile Plan Select plan");this.recordAction("CTA","Select plan","5G Unlimited+ Plus",i,await this.driver.getCurrentUrl())}
async chooseSim(){console.log("\n[7] SIM Selection");const t=/^(1|esim|e-sim)$/i.test(String(this.simType||"")),e=t?"eSIM":"Physical SIM",i=await this.visibleElements(By.css(t?"#b3-b1-b2-eSIM-input":"#b3-b1-b2-PhysicalSIM-input")).then(t=>t[0]);if(!i)throw new Error(`SIM option '${e}' was not found.`);await this.clickElement(i,e),this.result.selections.push({type:"SIM",value:e});const a=await this.captureAdobeWindow("SIM selection");this.recordAction("OPTION","SIM",e,a,await this.driver.getCurrentUrl());const r=await this.visibleElements(By.xpath("//button[normalize-space()='Next' or .//*[normalize-space()='Next']]")).then(t=>t[0]);if(!r)throw new Error("SIM Next CTA was not found.");await this.clickElement(r,"Next - SIM Selection");const s=await this.captureAdobeWindow("SIM Selection Next");this.recordAction("CTA","Next","SIM Selection",s,await this.driver.getCurrentUrl())}
async chooseSecurityAndWatch(){console.log("\n[8] Security / Add-ons");const t=await this.visibleElements(By.xpath("//*[contains(normalize-space(.),'Watch S11 46mm AL')]")).then(t=>t[0]);if(t){await this.clickElement(t,"Watch S11 46mm AL");const e=await this.captureAdobeWindow("Watch selection");this.recordAction("CTA","Watch S11 46mm AL","",e,await this.driver.getCurrentUrl())}const i=await this.visibleElements(By.xpath("//*[self::button or self::a or @role='button'][contains(normalize-space(.),'Continue') or contains(normalize-space(.),'Skip')]")).then(t=>t[0]);if(i){await this.clickElement(i,"Continue"),this.recordAction("CTA","Continue","Security / Add-ons",await this.captureAdobeWindow("Security Continue"),await this.driver.getCurrentUrl())}}
async chooseMobileNumber(){console.log("\n[9] Checkout / Mobile Number");const t=await this.visibleElements(By.css("#b3-BtnCheckoutWeb")).then(t=>t[0]);if(t){await this.clickElement(t,"Proceed to checkout");this.recordAction("CTA","Proceed to checkout","",await this.captureAdobeWindow("Proceed to checkout"),await this.driver.getCurrentUrl())}}
async deliveryFlow(){console.log("\n[10] Delivery");const t=await this.visibleElements(By.xpath("//*[self::button or self::a or @role='button'][contains(normalize-space(.),'Next') or contains(normalize-space(.),'Continue')]")).then(t=>t[0]);t&&(await this.clickElement(t,"Next - Delivery"),this.recordAction("CTA","Next - Delivery","",await this.captureAdobeWindow("Delivery Next"),await this.driver.getCurrentUrl()))}
async confirmAndPay(){console.log("\n[11] Confirm and Pay");const t=await this.visibleElements(By.css("#b3-Ack")).then(t=>t[0]);t&&!await t.isSelected().catch(()=>!1)&&(await this.clickElement(t,"T&Cs"),this.recordAction("CHECKBOX","T&Cs","Selected",await this.captureAdobeWindow("T&Cs"),await this.driver.getCurrentUrl()));const e=await this.visibleElements(By.xpath("//*[self::button or self::a or @role='button'][contains(translate(normalize-space(.),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'confirm and pay')]")).then(t=>t[0]).catch(()=>null);if(!e)throw new Error("Confirm and Pay CTA was not found.");await this.clickElement(e,"Confirm and Pay"),this.recordAction("CTA","Confirm and Pay","",await this.captureAdobeWindow("Confirm and Pay"),await this.driver.getCurrentUrl())}
async threeDsAndSuccess(){console.log("\n[12] 3DS + Success");await this.sleep(3e3);this.currentPageUrl=await this.driver.getCurrentUrl();await this.recordPage("Order Success",this.config.successPrefix||"checkout-success"),console.log("    Final URL: "+this.currentPageUrl)}
async run(){await this.createDriver();try{this.result.summary.steps=12;await this.login();await this.stepHome();await this.chooseDevice();await this.choosePdpOptions();await this.chooseIntent();await this.chooseStarPlan();await this.chooseSim();await this.chooseSecurityAndWatch();await this.chooseMobileNumber();await this.deliveryFlow();await this.confirmAndPay();await this.threeDsAndSuccess();this.result.summary.pagesVisited=this.result.pages.length,this.result.summary.adobeHits=this.result.hits.length,this.result.summary.ecommerceEvents=this.result.ecommerceEvents.length,this.result.summary.productsCaptured=this.result.products.length,this.result.summary.ordersCaptured=this.result.orders.length,this.result.summary.passed=this.result.pages.filter(t=>"PASS"===t.status).length,this.result.summary.failed=this.result.pages.filter(t=>"FAIL"===t.status).length,this.result.summary.status=this.result.errors.length?"FAIL":"PASS",this.result.finishedAt=new Date().toISOString();return this.result}catch(t){this.result.errors.push({timestamp:new Date().toISOString(),error:t.message||String(t),currentUrl:this.driver?await this.driver.getCurrentUrl().catch(()=> ""):""}),this.result.summary.status="FAIL",this.result.finishedAt=new Date().toISOString();throw t}finally{await this.close()}}
}
module.exports=PreSalesJourneyValidator;